-- Post-update "What's New" bullet lists, keyed by version string.
-- Add an entry for each release with noteworthy changes.
-- Omit a version to show no changelog on that update.
--
-- Example:
-- ["0.1.0"] = {
--     "New feature added",
--     "Bug fix for ...",
-- },

return {
    ["1.0.2"] = {
        "Automatically disable incompatible plugins",
        "Access reader menu from page browser",
        'Add "Report a Bug" button in Zen Settings > About',
        "Add in-app changelogs",
        "Add new quick settings buttons, hide when plugin not installed",
        "Add Bulgarian translation",
        "Bug fixes and performance improvements",
    },
    ["1.0.3"] = {
        "Fix: some quick settings buttons not showing",
        "Fix: language defaulting to english after plugin restart",
        "Bug fixes and performance improvements",
    },
    ["1.1.0"] = {
        "Add scroll bar with page numbers, jump to page, and buttons + skip (Library > Scroll bar)",
        "Add title/author strip (Library > Covers)",
        "Add padding to covers in list views",
        "Add Calibre search in navbar, label is Search (Navbar > Tabs)",
        "Add custom buttons (Quick settings > Buttons)",
        "Add LocalSend, Screenshot, Chess, Battery Stats to Quick Settings",
        "Add book information to context menu (Tap + hold book > Details)",
        "Collections and history have independent displays (Tap + hold Navbar)",
        "Support additional home folders (Library > Home folder)",
        "Support for non touchscreen devices",
        "Bug fixes and performance improvements",
    },
    ["1.2.0"] = {
        "Add Tags to Navbar (Settings > Navbar)",
        "Add custom tabs to Navbar (Settings > Navbar)",
        "Add filtering for all views",
        "Add dim finished books (Library > Covers)",
        "Add/remove from collections via context menu",
        "Add a toggle for folder stack spines (Library > Folders)",
        "Allow remove from history in context menu",
        "Better support for multiple home folders",
        "Up folder fixes and styling",
        "Fixed lag in folder/path chooser",
        "Fixed reader menu not opening on some devices",
        "Bug fixes and performance improvements",
    },
    ["1.2.1"] = {
        "Update flow enhancements (abort/prompt for network)",
        "Show a notification dot on Zen Settings icon when an update is available",
        "Adjust Zen cover image for screensaver",
        "Fix search (revert whole word searching)",
        "Fix Navbar tabs not showing after updating settings",
        "Fix unread status not fully resetting status",
        "Fix hide list borders not applying immediately",
        "Fix mosaic covers not showing in TBR",
        "Fix a rare issue where duplicate items could show in status bar/navbar",
        "Bug fixes and performance improvements",
    },
    ["1.3.0"] = {
        "Updated customization options for reader status bars (Reader > Top/Bottom Status bar)",
        "Add support for custom folder covers with image files",
        "Add support for more custom icons in Quick settings & Navbar",
        "Add support for setting font and font size in library",
        "Add color options for badges",
        "Updated placeholders for folders/books",
        "Add better support for legacy/non-touch devices",
        "Add refresh cached book info to edit menu",
        "Add toggle for whole word search matching (Global > Search)",
        "Add stack option for folder covers (Library > Folders > Covers)",
        "Add 2:3 and 3:4 cover ration in uniform covers (Library > Folders > Covers)",
        "Fix bug in lockdown mode allowing context menu when disabled via settings",
        "Fix KOReader behavior/bug - set status to reading on opening book",
        "Fix bug in search results always showing mosaic view",
        "Fixed bugs in OPDS & respect new 3:4 cover ratio",
        "Add Czech translation",
        "Bug fixes and performance improvements",
    },
    ["1.4.0"] = {
        "Migrated settings to new Zen UI settings file",
        "Add book info to reader top status bar (Reader > Top status bar)",
        "Refresh visuals for update checking",
        "Enhance Zen UI update security + method",
        "Add option to disable automatic update checking (About > Updates)",
        "Add changelog for previous versions (About > Updates)",
        "Add hook for deleting settings upon uninstalling",
        "Update quick lookup for next KOReader release",
        "Fix rare crash on background update check",
        "Fix uncached placeholder cover rendering",
        "Add Japanese translation",
        "Add Vietnamese translation",
        "Bug fixes and performance improvements",
    },
    ["2.0.0"] = {
        "IMPORTANT: This update has breaking changes, settings changed in v2.0 will not be saved if you go back to v1.x. Update via settings or completely delete old zen_ui.koplugin",
        "\u{F02DC} NEW Home page + widgets",
        "\u{F15FC} NEW Launcher",
        "Major performance improvements across the entire app",
        "Added default tab option for navbar (Navbar > Tab settings)",
        "Added automatic grouping of series into virtual folders (Library > Folders)",
        "Added stable pages support",
        "Added natural title sorting in context menu",
        "Added custom background (Library > Background)",
        "Added rotation options in Controls",
        "Added customizable screenshot timer in Controls > Buttons > Screenshot",
        "Added actions for authors/series/tags/ tabs and folders",
        "Updated Settings menus",
        "Updated Controls to launch plugins",
        "Improved 'Restore library location on exit' (Settings > Reader)",
        "Updated how settings are stored",
        "Reorganized/restructured",
        "Add option to flip Controls and Home/Library icon in menu (Settings > Controls)",
        "Optimizations reducing app size by 57%",
        "Added German translations",
        "Bug fixes",
    },
    ["2.1.0"] = {
        "Use full width for launcher icons",
        "Update home folder locking Zen mode (on/off/only in Zen Mode)",
        "Set reasonable max items for list mode - preventing crash",
        "Update end of book page to automatically mark finished and show next file button",
        "Update end of book page to return to library on page forward button/key",
        "Update slightly darker color of all progress bars",
        "Remove go to page in scrollbar for menus like icon picker, plugin list etc",
        "Fix discolored status bar color on color e-ink devices",
        "Fix a crash on KOReader 2024",
        "Fix some untranslated strings falling back to English",
        "Bug fixes",
    },
    ["2.2.0"] = {
        "Improve integration with Rakuyomi",
        "Add new action Zen UI - Library (Respects Restore last location)",
        "Add toggles in recently read strip widget to hide unread/finished books",
        "Add mark new and updated books as TBR (Advanced > Mark new and updated books as TBR)",
        "Update: Folder covers match order inside",
        "Add display mode per folder & collections",
        "Add separate display modes for OPDS (Advanced > Zen OPDS)",
        "Fixed a bug in Launcher settings showing reader actions",
        "Fixed a bug in reader top status bar showing after being hidden with action",
        "Fixed a bug in reader bottom status bar on starting KOReader with last file",
        "Bug fixes"
    },
    ["2.2.1"] = {
        "Fixed a bug with per folder display modes not applying",
        "Fixed a bug with per folder display mode not showing on real folders",
        "Fixed a bug multi page automatic series folders",
    },
    ["2.2.2"] = {
        "Better support for OPDS folders",
        "Status bar API for 3rd party plugins",
        "Bug fixes",
    },
    ["2.4.0"] = {
        "Even better Rakuyomi integration (Extras > Rakuyomi)",
        "Add row break in Launcher",
        "Add unified push/pull sync button to Actions",
        "Add Incognito mode to Controls/Actions",
        "Add AI Assistant icon in lookup/highlight",
        "Add Zen TOC action for gestures/launcher",
        "Add option to center books in Home strip widgets",
        "Add home API for plugin developers",
        "Update status bar API to allow images",
        "Update Zen Updater plumbing",
        "Update Zen Bug Reporter to send Android crash logs",
        "Update dim automatic folder covers when all books read (and dim enabled)",
        "Moved Navbar settings to Library > Navbar",
        "Moved Advanced settings to About > Advanced",
        "Moved Global settings to Extras",
        "Ignore English articles in title sort",
        "Persist library rotation state",
        "Bug fixes"
    },
    ["2.4.1"] = {
        "Fix reverse page scrolling applying to non Rakuyomi books"
    },
    ["2.4.2"] = {
        "Fix flat library layout",
        "Fix No Books Found using fallback if history is empty",
        "Improved logging",
        "Bug fixes"
    },
    ["2.4.3"] = {
        "Update quotes"
    },
    ["2.4.4"] = {
        "Fix time to book finished incorrect with stable pages"
    },
    ["2.5.1"] = {
        "Add testing framework",
        "Add Zen UI Reader margins to Advanced settings (About > Advanced)",
        "Add Reader themes (Reader > Reader themes)",
        "Add Control buttons to Launcher/Navbar",
        "Add Edit mode to Home/Stats",
        "Allow setting Launcher to be the default when you open the top Menu (Launcher > Open menu to Launcher)",
        "Auto suggest icons for Controls/Launcher/Navbar",
        "Standardize buttons menu for Controls/Launcher/Navbar",
        "Better sizing/spacing on home widgets",
        "Update menu icons",
        "Updated stats page + widgets (Extras > Stats)",
        "Updated ZenUpdater",
        "Add Ukrainian translation",
        "Bug fixes"
    },
    ["2.5.2"] = {
        "Allow top status bar in CBZ/PDF (Reader > Top status bar)",
        "Match top Menu icon to default Navbar tab",
        "Fix prevent auto night mode schedule from inverting Reader theme color"
    },
    ["2.5.3"] = {
        "Run plugin compat check immediately to prevent user install issues",
        "Improve Reader Themes in dark mode",
        "Fix line graph y-axis truncating too early",
        "Add Bluetooth toggle for supported Kindles in Controls/Navbar/Launcher + status bar icon",
        "Add TBR instructions to docs",
        "Fix translation bug",
        "Fix custom icon in menu for default tab"
    },
    ["2.5.4"] = {
        "Ensure wifi before showing ZenPM installer",
        "Adjust Zen screensaver book cover resolution",
        "Update testing emulator to KOReader 2026.07"
    }
}
